# Module 2 Problem Set


<div class="alert alert-block alert-success"><b>Problem 1</b></div>

Find the solution to the system of equations:
$$ x - 2y + z = 11 $$
$$ y + 2z = 1 $$
$$ x + y + 3z = 6 $$

In [1]:
import sympy as sym
# Use sympy package to display the equation
sym.init_printing()
#sym.solve()
x,y,z = sym.symbols('x,y,z')

solns = sym.solve([
    x - 2*y  + z - 11 , 
    y + 2*z - 1,
    x + y + 3*z - 6
    ],
    
    [x, y, z])
print(f"x= {solns[x]}")
print(f"y= {solns[y]}")
print(f"x= {solns[z]}")

x= 3
y= -3
x= 2


<div class="alert alert-block alert-success"><b>Problem 2</b></div>

A startup company spent `$`156036 on a combination of 151 tablets, laptops, and desktop computers. Each tablet cost `$`361, each laptop cost `$`1498, and each desktop computer cost `$`1884. 

Based on the structure of the company, they purchased twice as many tablets as laptops.

Let $x$ be the number of tablets purchased, $y$ the number of laptops purchased, and $z$ the number of desktops purchased. Set up the system of equations and solve it using Python.


In [2]:
import sympy as sym
# Use sympy package to display the equation
sym.init_printing()
#sym.solve()
x,y,z = sym.symbols('x,y,z')

# System of equations
# x + y + z = 151
# 361x + 1498y + 1884z = 150636
# x - 2y = 0

solns = sym.solve([
    x + y + z - 151 , 
    361*x + 1498*y + 1884*z - 150636,
    x - 2*y
    ],
    
    [x, y, z])
print(f"x= {solns[x]}")
print(f"y= {solns[y]}")
print(f"x= {solns[z]}")

x= 78
y= 39
x= 34


<div class="alert alert-block alert-success"><b>Problem 3</b></div>

A brass manufacturer makes three different type of wholesale brass blocks from copper and zinc according to the following matrix.

|        | High Brass | Muntz Metal | Gilding Metal |
|--------|------------|-------------|---------------|
| Copper | 65%        | 60%         | 95%           |
| Zinc   | 35%        | 40%         | 5%            |

In addition, the demand (in thousands of pounds) from Plant 1 is 7 High Brass, 5 Muntz metal, and 25 Gilding metal, and the demand from Plant 2 is is 12 High Brass, 3 Muntz metal, and 29 Gilding metal.

a) Make a 2x3 matrix B that contains the blending information in decimal form. 

b) Make a 3x2 matrix D for the demands at each plant. Plant 1 demands should be entered in column 1.

c) Find the matrix product to find each locations need for each type of metal.

d) if the price of zinc is `$`0.88 per pound and the price of copper is `$`3.29 per pound use python to calculate the total cost of Plant 1 and Plant 2.

In [3]:
# Matrix B
import numpy as np

# Create the blending matrix.
B = np.array([[0.65, 0.6, 0.95], [0.35, 0.4, 0.05]])
print()
print("Matrix B:")
print(B)

# Create the demand matrix.
D = np.array([[7, 12], [5, 3], [25, 29]])

print()
print("Matrix D:")
print(D)

# Calculate the matrix product.
product = np.matmul(B, D)

# Print the product.
print()
print("Matrix Product:")
print(product)

# Set the price of zinc.
zinc_price = 0.88

# Set the price of copper.
copper_price = 3.29

# Calculate the total cost for Plant 1.
plant1_cost = product[0, 0] * copper_price + product[1, 0] * zinc_price

# Calculate the total cost for Plant 2.
plant2_cost = product[0, 1] * copper_price + product[1, 1] * zinc_price

# Print the total cost.
total_cost_plant_1 = f"${plant1_cost*1000:,.2f}"
total_cost_plant_2 = f"${plant2_cost*1000:,.2f}"

print()
print("Total cost of Plant 1:",total_cost_plant_1)
print("Total cost of Plant 2:",total_cost_plant_2)



Matrix B:
[[0.65 0.6  0.95]
 [0.35 0.4  0.05]]

Matrix D:
[[ 7 12]
 [ 5  3]
 [25 29]]

Matrix Product:
[[31.3  37.15]
 [ 5.7   6.85]]

Total cost of Plant 1: $107,993.00
Total cost of Plant 2: $128,251.50


<div class="alert alert-block alert-success"><b>Problem 7</b></div>
Suppose A = [[-4, -4],[7, 7]], B = [[-1,4],[-5,-1]] and C = [[1. -4, -5],[7, 6, 0]]. Perform the following operations:

$$ A + B $$
$$B^TC$$

In [4]:
import numpy as np

# Define the matrices A, B, and C
A = np.array([[-4, -4], [7, 7]])
B = np.array([[-1, 4], [-5, -1]])
C = np.array([[1, -4, -5], [7, 6, 0]])

# (a) Find A + B
sum_AB = A + B
print("A + B:")
print(sum_AB)

# (b) Transpose(B) * C
transpose_B = np.transpose(B)
result = np.dot(transpose_B, C)
print("Transpose(B) * C:")
print(result)

A + B:
[[-5  0]
 [ 2  6]]
Transpose(B) * C:
[[-36 -26   5]
 [ -3 -22 -20]]


<div class="alert alert-block alert-success"><b>Problem 9: </b></div>

Solve the system using Cramer's Rule:

$$6x + 5y + z = -4$$
$$-6x - 4y - 2z = 2$$
$$-x + 4y - 3z = -13$$


In [5]:
import numpy as np

# Define the coefficient matrix and the constant vector
A = np.array([[6, 5, 1], [-6, -4, -2], [-1, 4, -3]])
b = np.array([-4, 2, -13])

# Calculate the determinant of A
D = np.linalg.det(A)

# Check if D is not zero
if D != 0:
    # Replace the first column of A by b and calculate the determinant
    A1 = A.copy()
    A1[:,0] = b
    Dx = np.linalg.det(A1)

    # Replace the second column of A by b and calculate the determinant
    A2 = A.copy()
    A2[:,1] = b
    Dy = np.linalg.det(A2)

    # Replace the third column of A by b and calculate the determinant
    A3 = A.copy()
    A3[:,2] = b
    Dz = np.linalg.det(A3)

    # Use Cramer's rule to find the solution
    x = round(Dx / D,2)
    y = round(Dy / D,2)
    z = round(Dz / D,2)

    # Print the solution
    print(f"x = {x}, y = {y}, z = {z}")
else:
    # Print that there is no unique solution
    print("There is no unique solution")

x = 3.0, y = -4.0, z = -2.0


<div class="alert alert-block alert-success"><b>Problem 11 </b></div>

Consider the matrix A:

$$
A = \begin{pmatrix}
5 & -4 & 1 & -3 \\
2 & -2 & 0 & -4 \\
1 & 2 & 4 & -1 \\
-2 & -5 & -2 & 5
\end{pmatrix}
$$

. To find the det(A), set up the cofactor expansion of A.


In [6]:
import numpy as np

A = np.array([[5,-4,1,-3],
              [2,-2,0,-4],
              [1,2,4,-1],
              [-2,-5,-2,5]
             ]
            )

# Calculating the det(A) with numpy
D = np.linalg.det(A)
print ("det(A) via numpy:", round(D,2))

# A11
A11 = A[1:, 1:]
D11 = np.linalg.det(A11)

# A12
A12 = A[1:, [0,2,3]]
D12 = np.linalg.det(A12)
 
# A13
A13 = A[1:, [0,1,3]]
D13 = np.linalg.det(A13)

# A14
A14 = A[1:, [0,1,2]]
D14 = np.linalg.det(A14)

# Coefficients from the first row
a11, a12, a13, a14 = A[0]

# Cofactor formula: Cij=(-1)**(i+j)Mij
C11 = (-1)**(1+1) * D11
C12 = (-1)**(1+2) * D12
C13 = (-1)**(1+3) * D13
C14 = (-1)**(1+4) * D14

# Calculating the determinant using cofactor expansion along the first row
D1 = a11 * C11 + a12 * C12 + a13 * C13 + a14 * C14
print ("det(A) via cofactor expansion:", round(D1,2))

# Checking the calculation of determinant via numpy compared to cofactor expansion
if round(D, 2) == round(D1, 2):
  print("The cofactor expansion is correct")
else:
  print("The cofactor expansion is incorrect")


det(A) via numpy: -300.0
det(A) via cofactor expansion: -300.0
The cofactor expansion is correct


<div class="alert alert-block alert-success"><b>Problem 12 </b></div>

Suppose R, M, N, H are square matrices such that det(RM) = 16, det (MN) = 11 and det(NH) = 5, Find the following in Python:

a. $$ det (RM^T)$$
b. $$ det(RN^{-1}) $$
c. $$ det(RMNH) $$
d. $$ det (RH) $$

In [7]:
import numpy as np

# R, C, D, H
# R, M, N, H

# Given determinants
det_RM = 16
det_MN = 11
det_NH = 5

# The transpose of M is the same as M since M is a square matrix.
# So, det(R * Transpose(M)) = det(R * M) = det(RM)
det_R_transpose_M = det_RM

# To find the inverse of N, we have det(R * inverse(N)) = det(R) / det(N)
det_R_times_inverse_of_N = det_RM / det_MN

# We can find the determinant of the product RMNH
# det(RMNH) = det(RM) * det(NH)
det_RMNH = det_RM * det_NH

# To find det(RH):
# det(R) * det(M) = det(RM) -> (1)
# det(M) * det(N) = det(MN) -> (2)
# det(N) * det(H) = det(NH) -> (3)

# Multiplying (1) (2) and (3)
# det(R) * det(M) * det(M) * det(N) * det(N) * det(H) = det(RM) * det(MN) * det(NH)
# Rearranging the terms
# (det(R) * det(H)) * (det(M) * det(N) * det(M) * det(N)) = det(RM) * det(MN) * det(NH)
# det(RH) * (det(MN) * det(MN)) = det(RM) * det(MN) * det(NH)

# => det(RH) = (det(RM) * det(MN) * det(NH))/det(MN)^2


print("a. det(R * Transpose(M)) =", round(det_R_transpose_M,2))
print("b. det(R * inverse(N)) =", round(det_R_times_inverse_of_N,2))
print("c. det(RMNH) =", round(det_RMNH,2))
print("d. det(RH) =", round((det_RM*det_MN*det_NH)/(det_MN**2),2))

a. det(R * Transpose(M)) = 16
b. det(R * inverse(N)) = 1.45
c. det(RMNH) = 80
d. det(RH) = 7.27


<div class="alert alert-block alert-success"><b>Problem 13:</b></div>

Suppose A = [[3, -2, 2], [0, -3, 0], [0, 0, 5]]. Find the sum of all the eigenvalues of A and the product of all the eigenvalues.

Plotting equations

In [8]:
import numpy as np

# Given matrix A
A = np.array([[3, -2, 2], [0, -3, 0], [0, 0, 5]])

# Calculate the eigenvalues of A
eigenvalues = np.linalg.eigvals(A)

# Find the sum of the eigenvalues
sum_of_eigenvalues = np.sum(eigenvalues)

# Find the product of the eigenvalues
product_of_eigenvalues = np.prod(eigenvalues)

print("Eigenvalues:", eigenvalues)
print("Sum of eigenvalues:", sum_of_eigenvalues)
print("Product of eigenvalues:", product_of_eigenvalues)

Eigenvalues: [ 3. -3.  5.]
Sum of eigenvalues: 5.0
Product of eigenvalues: -45.0


<div class="alert alert-block alert-success"><b>Problem 15:</b></div>

Given the following matrix, A, find each eigenvalue and a corresponding eigenvector.

$$
A = \begin{pmatrix}
-34 & 30 & -15 \\
-25 & 21 & -15 \\
12 & -6 & 15 
\end{pmatrix}
$$

<strong>Note there are infinitely many eigenvectors for an eigenvalue depending on the scaling factor.</strong><p>

<em>The following Python code will compute the eigenvectors symbolically, so it's more likely to provide you precise or integer results. Hopefully, this will get you closer to more satisfying answers that you might find in the examples</em><p>

In [9]:
from sympy import Matrix

# Define the matrix
A = Matrix([[-34, 30, -15], [-25, 21, -15], [12, -6, 15]])

# Compute the eigenvalues and eigenvectors
eigenvalues = A.eigenvals(multiple=True)
eigenvectors = A.eigenvects()

# Output the results
for val, mult, vec in eigenvectors:
    print(f"Eigenvalue: {val}")
    for v in vec:
        print(f"Eigenvector: {v}")

Eigenvalue: -9
Eigenvector: Matrix([[-3], [-2], [1]])
Eigenvalue: 5
Eigenvector: Matrix([[-5/3], [-5/3], [1]])
Eigenvalue: 6
Eigenvector: Matrix([[-3/2], [-3/2], [1]])


<div class="alert alert-block alert-success"><b>Changes to Notebook</b></div>
<ul>
    <li>Adjusted answer output display for Problems 1+2</li>
    <li>Fixed dollar amounts in markdown by surrounding the dollar-sign with backticks for Problems2+3</li>
    <li>Added Problem 11</li>
    <li>Added more comments for the intermediate steps of Problem 12 code</li>
    <li>Added Problem 15</li>
</ul>